name: Build CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Node.js Version 설정
      uses: actions/setup-node@v3
      with:
        node-version: 20
        cache: 'npm'
    
    - name: 의존성 설치
      run: npm ci
    
    - name: 빌드 시도
      run: npm run build 